name: HissEllerDiss

networks:
  api-network:
  service-network:

volumes:
  rabbitmq-data:

services:

  #RabbitMQ container
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: ${RABBITMQ_HOSTNAME}
    container_name: HissEllerDiss-rabbitmq
    ports:
      - ${RABBITMQ_EXT_PORT}:${RABBITMQ_INT_PORT}
      - ${RABBITMQ_EXT_MANAGEMENT_PORT}:${RABBITMQ_INT_MANAGEMENT_PORT}
    networks:
      - service-network
      - api-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASSWORD}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://${RABBITMQ_HOSTNAME}:${RABBITMQ_EXT_MANAGEMENT_PORT}
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 30s   

  #ASP.NET Service container      
  service:
    build: ./HissEllerDiss-service
    image: mindblaster303/hissellerdiss-service
    hostname: ${SERVICE_HOSTNAME}
    container_name: HissEllerDiss-service
    ports:
      - ${SERVICE_EXT_PORT}:${SERVICE_INT_PORT}
    networks:
      - service-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://${SERVICE_HOSTNAME}:${SERVICE_EXT_PORT}/api/hissellerdiss
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ASP.NET Core API container
  api:
    build: ./HissEllerDiss-api
    image: mindblaster303/hissellerdiss-api
    hostname: ${API_HOSTNAME}
    container_name: HissEllerDiss-api
    ports:
      - ${API_EXT_PORT}:${API_INT_PORT}
    networks:
      - api-network
      - service-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      service:
        condition: service_healthy
